services:
  - name: chickenviken-api
    type: web
    runtime: node
    region: ohio  # Choose a region close to your users
    buildCommand: cd server && npm install
    startCommand: cd server && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
  - name: chickenviken-user-app
    type: web
    runtime: static
    buildCommand: cd user-app && npm install && npm run build
    staticPublishPath: user-app/dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - name: chickenviken-admin-app
    type: web
    runtime: static
    buildCommand: cd admin-app && npm install && npm run build
    staticPublishPath: admin-app/dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
